### ISSUE TITLE
An error in "Definitions of data members and classes/structs"?

### ISSUE THREAD

**Issue by alessandro-gentilini** [MicrosoftDocs/windows-devdocs-team#3]
Hello,
I am not a language lawyer but it seems to me there is an error in
https://github.com/MicrosoftDocs/windows-devdocs-team/blob/main/bite-sized-cpp/posts/019.md

> ```
> // MathLibStruct.h
> struct MathLibStruct // A class/struct definition
> {
>     float SquareOf(float); // A member function declaration
>     float f1 = 3.14f;      // A data member definition
>     float f2;              // Another data member definition
> };
> ```
> 
> So data members `f1` and `f2` are both defined, because they're both initialized in this case (even if it's with a default value, as in the case of `f2`). 

Maybe I am wrong, but my interpretation of Stroustrup is that `f2` will have an undetermined value and not a default one, see the excerpt from The C++ Programming Language (4th Edition):
![Screenshot_20210612_162252](https://user-images.githubusercontent.com/2438459/121779166-9fb87480-cb9a-11eb-8862-0ca456110f2c.png)
![image](https://user-images.githubusercontent.com/2438459/121779260-1a818f80-cb9b-11eb-87af-7a6d82bd93f7.png)

**Comment by stevewhims** [comment]
Thanks, @alessandro-gentilini, I believe you're right. I've fixed that post, I think. Does that look correct now?

Many thanks!
Steve

**Comment by alessandro-gentilini** [comment]
@stevewhims Thank you, now it looks like correct. There was just a small typo I fixed with the pull request https://github.com/MicrosoftDocs/windows-devdocs-team/pull/4

**Comment by stevewhims** [comment]
Great, thanks, @alessandro-gentilini. The PR is completed, too. :)
